### ISSUE TITLE
Unable to launch on Linux due to the use of an unsupported color in the GUI

### ISSUE THREAD

**Issue by vyrjana** [hprodenburg/DECiM#1]
Hello,

I encountered a bug when trying to launch DECiM on Linux since the color `"SystemButtonFace"` that is used here https://github.com/hprodenburg/DECiM/blob/ccfd9c372539818cfa4f1fcc5f0908214f672027/src/ecm_user_input.py#L108 is [only supported on Windows and macOS](https://tcl.tk/man/tcl8.6/TkCmd/colors.htm) (see the *PORTABILITY ISSUES* section further down in the linked page). I was able to fix this issue by modifying that line of code to use a color that is platform-agnostic.

**Comment by hprodenburg** [comment]
Thank you for pointing this out and providing a simple fix; I've changed the `disabledforegroundcolor` to `SlateGray1`. That should fix it.
