### ISSUE TITLE
Issues with some of the plots

### ISSUE THREAD

**Issue by vyrjana** [hprodenburg/DECiM#2]
Hello again,

I noticed a few issues with some of the plots.

## Complex plane admittance

The real and imaginary parts of the admittance (i.e., Re(1/Z) and Im(1/Z)) are not actually being plotted. Instead, the current implementation plots 1/Re(Z) and -1/Im(Z):

https://github.com/hprodenburg/DECiM/blob/a7a8ead94f5b4c419fa8920eb49e32a9380d14ff/src/ecm_plot.py#L399

![admittance-before](https://github.com/user-attachments/assets/f426f657-17e2-4df2-bef0-c6cf3fcd7954)

Also, it would be great if the plot used 1:1 scales for the two axes to avoid distorting shapes. [Here's a link to the matplotlib documentation that shows how this can be accomplished](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/axis_equal_demo.html). The approach demonstrated in the lower left-hand corner (`.axis("equal")`) seems suitable. Here's what it looks like when plotting the correct data and also using 1:1 scales.

![admittance-after](https://github.com/user-attachments/assets/005da9d8-33e0-4d81-ae28-4fd7511d054d)

## Complex plane impedance

It would be great if this also used axes with 1:1 scales.

## Z' and Z" vs. frequency

The y-axis label for Z"  should be preceded by a negative sign since -Z" is what is being plotted in the implementation:

https://github.com/hprodenburg/DECiM/blob/a7a8ead94f5b4c419fa8920eb49e32a9380d14ff/src/ecm_plot.py#L662

Also, it seems that sometimes not all points are being plotted on the secondary y-axis. For example, if I load `examples/RbOH_xH2O/CH3_cool_40C_2.csv` and plot it as `Z' and Z" vs. frequency`, then a few of the highest frequency Z" points are missing but the corresponding Z' points are present. The exact number of points that are missing seems to vary depending on the file (e.g., only one is missing when plotting `examples/Li_Graphite_Half_Cell/Graphite_EIS_after_charge_discharge_study_100kHz_10mHz.txt`).

![bug-example](https://github.com/user-attachments/assets/82075bb2-4ca8-4e67-9334-666452f64464)

## Y' and Y'' vs. frequency

Same issue as with the complex plane admittance plot regarding what is actually being plotted (i.e., currently plotting 1/Re(Z) and -1/Im(Z) instead of Re(1/Z) and Im(1/Z)):

https://github.com/hprodenburg/DECiM/blob/a7a8ead94f5b4c419fa8920eb49e32a9380d14ff/src/ecm_plot.py#L548

https://github.com/hprodenburg/DECiM/blob/a7a8ead94f5b4c419fa8920eb49e32a9380d14ff/src/ecm_plot.py#L574

**Comment by hprodenburg** [comment]
Thanks for pointing this all out! I've made the following changes:

- The mistakes in the admittance plots are now fixed.
- Complex plane plots now have fixed aspect ratios, so circles are now indeed circular and not distorted.
- Axis labels have been updated.

Regarding the missing data in (Z', -Z''), I do not know what causes this. I may have time to look deeper into in the near future, but I can't promise that it will be fixed soon.

**Comment by vyrjana** [comment]
Great!

I forgot to mention that the Y' and Y'' vs f plots are also affected by the missing points. However, I've pinpointed the source of the issue: the missing points are all negative values and logarithms of negative numbers are undefined. Therefore they cannot be plotted on a y-axis that is set to use a logarithmic scale. I should have thought of that sooner since I dealt with this issue a while back.

**Comment by hprodenburg** [comment]
That makes sense. I think there is no way to address this other than not using a log-scale. I will close this issue.
